### ISSUE TITLE
Does not work with OnPrem TFS installation

### ISSUE THREAD

**Issue by peterliapin** [GersonDias/toggl-buttonVSOExtension#5]
I use the add-in with TFS online for almost a year and it works really well. Today I tried to install it on out OnPrem TFS 2015 server and it does not work there. I can see "Track your time" button in the toolbar of any "edit workitem" form but when I click it nothing happens.

If I look at javascript console log there is an error:

> VSS.SDK.js:1100 Mixed Content: The page at 'https://vso-toggl.azurewebsites.net/TogglButton' was loaded over HTTPS, but requested an insecure stylesheet 'http://our-tfs-server-address/tfs/_static/tfs/Dev14.M102/App_Themes/Default/jquery-modified'. This request has been blocked; the content must be served over HTTPS.

Could you please support HTTP addresses as well?

**Comment by GersonDias** [comment]
@petrlyapin thanks for your interest in my extension. I'm afraid that VSTS extensions need to be hosted or make calls only for https addresses (since *.visualstudio.com is an HTTPS address...). Anyway, maybe you can do your tfs instalation as HTTPs with a self signed certified, if your company doesn't have a valid certificate...

**Comment by peterliapin** [comment]
@GersonDias thank for your reply. As you host the site in Azure it supports both http and https calls out of the box. I.e. if you load the original http://vso-toggl.azurewebsites.net/TogglButton page via HTTP from the VS add-on it will all work. Can not you just use a protocol-relative URL like `//vso-toggl.azurewebsites.net/TogglButton` to load the page from the VS add-on, so it works using the same protocol as the host TFS? This way it will support both HTTP and HTTPS installations.
