### ISSUE TITLE
Clicking Track time in VSO fails - unable to access https://vso-toggl.azurewebsites.net/

### ISSUE THREAD

**Issue by davidshorter** [GersonDias/toggl-buttonVSOExtension#6]
https://vso-toggl.azurewebsites.net/ looks to have been stopped, which makes the toggl time tracking feature to fail silently

![image](https://cloud.githubusercontent.com/assets/13352856/26615377/82b54d7c-461a-11e7-9047-4b3792a93d2e.png)

Confirmed by heading to https://vso-toggl.azurewebsites.net

![image](https://cloud.githubusercontent.com/assets/13352856/26615352/4afc5326-461a-11e7-8485-a9b0f5d6e75d.png)

**Comment by GersonDias** [comment]
David,

Thanks for using my extension. I already fixed the issue.

Best Regards,

Gerson Dias

2017-05-31 6:02 GMT+02:00 David Shorter <notifications@github.com>:
